### ISSUE TITLE
publicaties in de kijker tonen in zoekresultaten weergave 10 resultaten per pagina

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#130]
assigned @JorisLambrechts 

Publicaties "In de kijker" verschijnen enkel bij instelling 50 resultaten per pagina, niet bij 10 of 20 resultaten per pagina. 

![capture](https://cloud.githubusercontent.com/assets/3798589/3722417/95d7ab22-1669-11e4-8fbc-34f011b6f0ca.JPG)
![capture1](https://cloud.githubusercontent.com/assets/3798589/3722418/95d8764c-1669-11e4-9848-0719ed7aa576.JPG)

**Comment by roxannewyns** [comment]
@JorisLambrechts Kan je standaard 50 resultaten laten zien voor zowel projecten als publicaties.

**Comment by samalloing** [comment]
maar is het probleem niet gemakkeliker op te lossen door de featured ook toe te voegen aan alle publicaties?

**Comment by roxannewyns** [comment]
Volgens mij niet, want dan verschijnen er te veel in recente publicaties. Ook bij projecten, featured project items worden onder lopende projecten gestoken denk ik.

**Comment by samalloing** [comment]
nee, want nu is het probleem dat bij de query er een opsplitsing gebeurt tussen featured en alles. En daarom zijn er 8 featured en 2 bij alle (samen 10). als je die 8 nu bij de 2 voegt, dan heb je er 10. De recente daar blijf je vanaf.

Je ziet hetzelfde trouwens bij 50. De som van de recente + alle = 50

**Comment by roxannewyns** [comment]
opgelost:
indien metadata veld "recent" als waarde "ja" heeft, staan ze bij rencente publicaties
publicaties die featured zijn verschijnen in lijst "publicaties bestellen".
