### ISSUE TITLE
add rabbitmq support to omeka

### ISSUE THREAD

**Issue by samalloing** [libis/CAG#145]
Omeka uses Beanstalk (and phaenstalk = php client) for long running jobs. It has a an adapter interface to add more jobs processing adaptors. We should make a rabbitmq adapter (relevant files are in application/libraries/Omeka/Job/ and the adapter fiiles are in application/libraries/Omeka/Job/Dispatcher/Adapter

cc @JorisLambrechts @roxannewyns

**Comment by roxannewyns** [comment]
geen prioriteit lijkt me.
