### ISSUE TITLE
Speciale tekens worden verkeerd weergegeven in het overzicht en afdrukversie,

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#157]
assigned @JorisLambrechts 
Speciale tekens worden verkeerd weergegeven in het overzicht en afdrukversie,  Zie bijv. afdrukversie exhibits/show/appels?action=print

**Comment by JorisLambrechts** [comment]
Is dit op "/cag/alle-verhalen"? Want bij mij staat er gewoon België (op de server).

**Comment by roxannewyns** [comment]
lijkt in orde te zijn nu, weet niet waarom. de fout in het print screen vb. hierboven en andere gevallen zijn toch verdwenen.

**Comment by samalloing** [comment]
zal door deze 9c08b80a69044866ee9199e657f87711dc1d697d commit zijn
