### ISSUE TITLE
Bij een agendaitem te verwijderen is er een exception doordat een object null is

### ISSUE THREAD

**Issue by samalloing** [libis/CAG#167]
Een agendaitem werd verwijderd en geeft op de resultatenpagina een error doordat het $item object null is. Het is nu tijdelijk gefixed, maar waarschijnlijk is het probleem dat een record niet verwijderd is uit de Solr index en wel uit de databank.
zie tijdelijke fix: 7574f535518578f16ebad0f1305520698577ef04

**Comment by JorisLambrechts** [comment]
lijkt me opgelost

**Comment by JorisLambrechts** [comment]
door o.a. dit https://github.com/libis/CAG/commit/f71e87744502fd9c471651e559d49757b940f900
