### ISSUE TITLE
Agenda items en nieuwsberichten chronologisch tonen op aanmaak: nieuwste eerst 

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#173]
assigned @JorisLambrechts 
Momenteel staan de oudste nieuwsberichten en agenda punten bovenaan. 
Verander de rangschikking met de meest recent aangemaakte berichten bovenaan. 
Soms worden items op later tijdstip nog gewijzigd. Misschien heeft dit ook invloed op de rangschikking? Een mogelijke oplossing is een datumveld toevoegen en op basis daarvan rangschikken?

**Comment by JorisLambrechts** [comment]
ook voor publicatie en projecten

**Comment by roxannewyns** [comment]
publicatie sorteren op het dublincore veld "Datum". Kan dit in combinatie met een query laatst aangemaakt? Zo komen de recentste publicaties van 2014 bovenaan te staan.

**Comment by roxannewyns** [comment]
idem voor projecten
