### ISSUE TITLE
pagina /verhalen/voedsel geeft nog themaverhalen met tag 'oogst' weer

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#179]
assigned @JorisLambrechts 

Op de pagina /verhalen/voedsel staan ook nog de themaverhalen met de tag 'oogst'. E.g. De grote trek oostwaarts van de aardbei.

![capture](https://cloud.githubusercontent.com/assets/3798589/5705987/898d9a6e-9a7d-11e4-9e30-2bd7c4592451.JPG)

Op deze pagina mogen enkel die themaverhalen/exhibits verschijnen die als tag 'voedsel' hebben.

**Comment by JorisLambrechts** [comment]
dit is al in orde (nu wel de juiste tag). De wijziging zit in de simple page zelf dus staat niet op github.
