### ISSUE TITLE
collecties - te veel items getoond op kaart 

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#182]
assigned @JorisLambrechts 

De locatie van de instellingen wordt juist getoond indien het een zoekresultaat van 10 is, maar bij het opgeven van tonen van 50 zoekresultaten zijn er plots veel te veel locaties zichtbaar, ook van objecten.

![capture](https://cloud.githubusercontent.com/assets/3798589/5818422/e030c150-a0b5-11e4-890e-0f3ec0f9a5d4.JPG)

**Comment by roxannewyns** [comment]
de kaart wordt niet meer getoond nu.

**Comment by JorisLambrechts** [comment]
bij ziet het er nog ok uit, kan je een voorbeeld geven van waar het niet meer werkt? (ik zoek op 'maria' en krijg zowel van 10, 20 en 50 resultaten een kaart die lijkt te kloppen)

**Comment by JorisLambrechts** [comment]
Blijkbaar zijn er geen geolocation referenties meegegeven maar is enkel de coverage ingevuld. De geolocation-kaart houdt enkel rekening met de geolocation objecten (coördinaten).

**Comment by roxannewyns** [comment]
@JorisLambrechts 
Je moet de georeference opzoeken op basis van de coverage en deze toevoegen in de database. Sam heeft hier al een applicatie voor geschreven. 

cc @samalloing

**Comment by JorisLambrechts** [comment]
De gegevens zijn opgeladen. Item 48742 (in Bree) bijvoorbeeld, staat nu wel op de kaart.

**Comment by roxannewyns** [comment]
assigned @JorisLambrechts 
Je hebt dit voor objecten gedaan, maar het moet ook gebeuren voor alle items van het itemtype 'Collecties'. 
In het begin verscheen er onderaan de zoekresultaten .../solr-search/results/index/page/2?q=*&facet=itemtype%3A"Collectie" een kaart met alle items van het type 'collectie' er op.

**Comment by roxannewyns** [comment]
Voor de items van het item type collectie moet je de locatie opzoeken op basis van de waarde in het veld "Stad" (element ID = 208).

**Comment by JorisLambrechts** [comment]
Stad is nu ook in orde
