### ISSUE TITLE
collecties - 2 x antwerpen in facet provincie

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#186]
assigned @JorisLambrechts 

De provincie Antwerpen komt tweemaal voor als filter, met eenmaal 16 collecties en eenmaal 1 collectie. De afwijking zit bij Bijenteeltmuseum Kalmthout (/items/show/60510/).

![capture](https://cloud.githubusercontent.com/assets/3798589/5836542/8640ba34-a177-11e4-9d23-38a3e39da602.JPG)

**Comment by samalloing** [comment]
dat zal gewoon een spatie in de data. ik heb het aangepast
