### ISSUE TITLE
alle resultaten in filter alfabetisch sorteren

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#187]
assigned @JorisLambrechts 

resultaten filters alfabetisch sorteren i.p.v. op relevantie. 

![screenshot1](https://cloud.githubusercontent.com/assets/3798589/5897234/ea816020-a541-11e4-8808-dbbc7b050054.png)

**Comment by JorisLambrechts** [comment]
Het was wel een instelling van de plugin (/cag/admin/solr-search)
