### ISSUE TITLE
niet alle steden of provincies getoond

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#189]
Bij collecties worden niet alle  steden of provincies weergegeven die er zouden moeten zijn
Bijvoorbeeld bij steden toont de filter resultaten van A tot G.

**Comment by JorisLambrechts** [comment]
Dit was ook een instelling van de plugin, het staat nu op 300. Alle objectnamen ga je er wel nooit in krijgen (dat wordt een half uur scrollen als ze die allemaal willen zien).
