### ISSUE TITLE
afbeeldingen (en soms tekst) verdwenen bij verhaal Kebab met mayonaise

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#191]
cc @JorisLambrechts 

tekst verdwenen op o.a. pagina /exhibits/show/kebab/migratie/mijnstreek
foto's verdwenen op allen pagina's

Misschien is er iets misgegaan met bij de vorige migratie?

**Comment by samalloing** [comment]
De gegevens zitten niet in de databank, vandaar dat er geen tekst wordt getoond. ik weet niet of er ooit tekst is geweest.

De afbeeldingen zijn opnieuw gelinkt en zouden in orde moeten zijn.

**Comment by roxannewyns** [comment]
@samalloing 

Kan je aan hoofdstuk 1.1 'Naar de mijnstreek' de afbeelding koppelen a.u.b. Diantha heeft de tekst terug toegevoegd (CA: object_id/29056, HVL: 59630).

**Comment by samalloing** [comment]
aangepast
