### ISSUE TITLE
icoontje creativecommens niet zichtbaar

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#192]
assigned @JorisLambrechts 

Het creativecommens icoontje is niet meer zichtbaar, er staat enkel tekst. 

![capture](https://cloud.githubusercontent.com/assets/3798589/6146430/c96fbac8-b1ec-11e4-982c-7f34973be327.JPG)

**Comment by JorisLambrechts** [comment]
Bij dit item, stond er een spatie te veel op het einde van het licentieveld. Ik heb nog een aantal items getest en daar lijkt het wel in orde.

**Comment by samalloing** [comment]
trim de input om dit probleem te voorkomen
