### ISSUE TITLE
pagina verplaatsen in verhaal geeft foutmelding

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#193]
assigned @JorisLambrechts 
cc @samalloing 

CAG wil een pagina verplaatsen in het verhaal "De grote trek oostwaarts... van de aardbei" (/exhibits/edit/100200). Het verslepen lukt, maar bij saven krijg je 'Omeka stuitte op een fout'.
Een andere pagina kon ik wel verplaatsen en saven. 

![verhaleniii](https://cloud.githubusercontent.com/assets/3798589/6146520/eba96bc4-b1ed-11e4-9898-ca5da50ff573.jpg)

**Comment by JorisLambrechts** [comment]
Dit heeft met de slugs te maken, die zijn meestal gewoon gelijk aan de volgorde (dus 1, 2, 3, ..) in het dat hoofdstuk.

Maar als je ze dan naar een ander hoofdstuk wil verschuiven waar die volgorde ook al bestaat krijg je een slug die dubbel is (in dit geval 2 keer 2).

Je moet hier dus de nummers op voorhand even aanpassen in elke pagina om plaats te maken voor de nieuwe. (of enkel de pagina die je gaat verplaatsen een andere slug geven die nog niet voorkomt in het nieuwe hoofdstuk)
