### ISSUE TITLE
sorteren publicatie op datum

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#194]
assigned @JorisLambrechts 

Sorteren van publicatie op datum geeft problemen. Bij een kleine aanpassing en opnieuw saven van een publicatie, komt deze weer helemaal onderaan te staan. 
Ik denk dat de sorteren gebeurde op basis van een combinatie tussen sorteren op laatst aangepaakt en sorteren op het datum veld. 

Sorteer enkel en alleen op basis van het datumveld (dc:datum). De meest recente datum bovenaan.

**Comment by JorisLambrechts** [comment]
Dit is solr zelf, die zet een aangepast item achteraan in de index (bij wijze van spreken). Dit is bij alle items zo, niet enkel publicaties. Bij een volledige reïndexering wordt dat wel weer rechtgezet maar dat is natuurlijk geen oplossing.
