### ISSUE TITLE
bekijken/verwijderen van Libis_treeIntoArray code

### ISSUE THREAD

**Issue by samalloing** [libis/CAG#196]
De code voor Libis_treeIntoArray geeft een error in de query naar de databank: Table 'omeka_cag.omeka_record_types' doesn't exist. De relevant lijnen zijn 363 van custom.php . Ook  themes/CAG/simple-pages/page/show.php lijn 41 is waar de code wordt opgeroepen.

cc @roxannewyns

**Comment by JorisLambrechts** [comment]
/werktuigen stond nog publiek en verwees naar oude code
