### ISSUE TITLE
beelden herschikken in database

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#198]
assigend @JorisLambrechts 

In de databank moet de juiste volgorde van de beelden nog aangepast worden. Op basis van de nieuwe implementatie sortering op ID #190

**Comment by JorisLambrechts** [comment]
Zijn alle items dan verkeerd of zijn het er maar een paar?

**Comment by roxannewyns** [comment]
Geen idee hoeveel. Ik heb verschillende voorbeelden doorgekregen, dus ik denk dat de meeste niet in orde zijn. De rangschikking gebeurde random.

**Comment by samalloing** [comment]
geef de volgorde uit collectiveaccess door aan Joris

**Comment by roxannewyns** [comment]
assigned @JorisLambrechts 
Deze staan nog fout :
/cag/items/show/60411
/cag/items/show/60402
/cag/items/show/60432
/cag/items/show/60339
/cag/items/show/60345
/cag/items/show/60390

**Comment by roxannewyns** [comment]
@samalloing 

Kan je naast de rangschikking van bovenstaande items ook bij volgende items de dubbels verwijderen
/items/show/60306/ (eerste foto zelfde als 2de)
/items/show/60303/ (eerste foto is dezelfde als derde foto) 
Of mag ik dit via de dataabse doen? Waar zit dat dan juist?

**Comment by samalloing** [comment]
aangepast. De dubbels zijn ook verwijderd
