### ISSUE TITLE
nieuwsbrief

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#206]
assigned @JorisLambrechts 

Wanneer je de nieuwsbrief in Outlook bekijkt, dan verwijst de link om terug naar boven te gaan (‘naar boven’) je naar het midden van de pagina ipv naar boven. ("html: <p style="font: 11px; line-height: 12px; color: #e9af10;"><a style="text-decoration: none; color: #e9af10;" href="#top"> naar boven </a></p>" ) 

In gmail werkt de link in het geval helemaal niet. 

De gearchiveerde versie op HVL werkt wél volledig naar behoren.

**Comment by JorisLambrechts** [comment]
kan je me die nieuwsbrief doorsturen?

**Comment by JorisLambrechts** [comment]
Dit is een van de problemen met html in mails. De #top werkt niet altijd (niet in gmail en niet helemaal juist vanaf outlook 2007). Ik heb in de laatste nieuwsbrief een <a name='top'></a> in de hoofding gezet. Verwijzen naar een 'name' heeft het meeste kans op slagen.

De links van hun overzicht bovenaan de pagina verwijzen ook via een 'name' naar de hoofdstukken dus die staan al goed.

https://www.campaignmonitor.com/blog/post/3322/the-trouble-with-anchor-links-in-email-newsletters hier staat een tabel met uitleg
