### ISSUE TITLE
recente publicaties

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#209]
assigned @JorisLambrechts 

Op dit ogenblik komen alle items van het itemtype 'publicatie' die gemarkeerd staan als 'aanbevolen / featured' in de lijst van recente publicaties terecht.
In: /cag/solr-search/results?q=&facet=itemtype:"Publicatie"

Het probleem is dat om een item in de lijst van publicaties bestellen te laten verschijnen, ze deze ook op 'aanbevolen / featured' moeten zetten. 
In: /cag/contact/bestel.  

Een publicatie die nog te bestellen is, is niet noodzakelijk een recente publicatie. Hier moet dus een onderscheid gemaakt worden. 
Misschien kunnen we een metadata veld 'recente publicatie' toe voegen aan het itemtype 'publicatie'. Indien hier ja staat, dan verschijnt het item in de lijst van recente publicaties. 

De 'aanbevolen / featured' functie blijft dan behouden voor items die in de lijst 'publicaties bestellen' terecht moeten komen.

**Comment by JorisLambrechts** [comment]
We kunnen ook gewoon enkel kijken op datum en niet op featured, dan heb je enkel de recente. En bij de te bestellen publicaties wel filteren op featured en niet op recente datum (zo staat het daar al ingesteld).

Nu zijn de recente publicaties eigenlijk niet recent :) maar gewoon de featured geördend op datum.

**Comment by roxannewyns** [comment]
@JorisLambrechts 
Bij controle nog iets opgemerkt. Ik denk dat we toch beter nog een extra criterium inbouwen. Ze hebben namelijk niet zoveel recente publicaties en daardoor staat er ook nog publicaties in de lijst staan die dateren van 2002 http://www.hetvirtueleland.be/cag/solr-search/results?q=&facet=itemtype:%22Publicatie%22 

Dus in lijst Meer recente publicaties http://www.hetvirtueleland.be/cag/bronnen/eigenpublicaties
BV:
-	Enkel waar er in een nieuw metadata veld ‘recente publicatie’ de waarde Ja staat.
-	Daarnaast ook nog sorteren op datum

De weergave op volgende pagina lijkt wel ok http://www.hetvirtueleland.be/cag/bronnen/eigenpublicaties

**Comment by JorisLambrechts** [comment]
er is een metadataveld 'recent', als dat op ja staat is het een recente publicatie

moesten er binnenkort genoeg echt recente publicaties zijn kunnen we op datum filteren
