### ISSUE TITLE
nieuwste toevoegde agenda- en nieuwsitems komen op 2de pagina te staan

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#214]
De nieuwste toevoegde agenda- en nieuwsitems komen niet op de eerste, maar pas op de volgende pagina te staan, bij een aantal hoger dan 50 items in totaal (bij standaard pageview van 50 items). Deze moten bovenaan de 1st pagina komen te staan want CAG wil liever geen oude nieuwsberichten verwijderen om onder de 50 te blijven. 

Kan je dat redelijk eenvoudig aanpassen? Anders kunnen we het aantal zoekresultaten nog verhogen, maar dan stoten we binnenkort weer op problemen.

**Comment by roxannewyns** [comment]
Dit kon niet dacht ik omdat we de items niet kunnen sorteren met Solr. Klopt dat? In principe is sorteren op laats toegevoegde item ok.

**Comment by JorisLambrechts** [comment]
Ook op id krijg ik het niet gesorteerd. We kunnen er eventueel wel de gewone browse pagina (mysql) voor gebruiken.

**Comment by roxannewyns** [comment]
Dat kan misschien ook want ik denk dat de browse functie hier niet zo van belang is. Maar misschien is de oplossing die je gaf voor Flandrica ook hier beter?

"Dus bijvoorbeeld in flandrica als je zoekt op 'maria' en vervolgens facets gebruikt is alles gewoon gesorteerd naar relevantie met de term 'maria' en wordt er niet naar id gekeken, maar als je direct naar een collectie-pagina gaat (zonder een extra zoekterm) gebruik je enkel facets en verlies je dus geen relevantie door te sorteren op id."
