### ISSUE TITLE
rosetta plugin implementeren

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#222]
Deze omeka site heeft enkel de digitool plugin waardoor afbeeldingen met de Rosetta EI niet getoond worden.  bv. /cag/admin/items/edit/67789 (item niet openbaar)

**Comment by JorisLambrechts** [comment]
Ik moest enkel de url aanpassen in de plugin-configuratie.

De thumbnails werken nu dus al overal maar de links naar de VIEW of HIGH moet ik nog instellen.

**Comment by JorisLambrechts** [comment]
De afbeeldingen werken. Ik heb de nieuwe rosetta-plugin wel niet geïnstalleerd omdat ik daarvoor ook alle huidige pids moet importeren als files wat veel tijd kan kosten en we misschien pas bij een eventuele overgang naar omeka-s moeten overwegen. 

Het kan natuurlijk altijd als het later noodzakelijk wordt.
