### ISSUE TITLE
quick search results geeft 404 voor exhibit items

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#223]
assigned @JorisLambrechts 

Wanneer je op een exhibit item klikt vanuit de quick search zoekresultaten, krijg je een 404 pagina. 
![capture](https://cloud.githubusercontent.com/assets/3798589/16199271/3da556da-3709-11e6-89ed-a8b2a6403b93.JPG)

Het probleem zit hem in de URL waar een stuk in ontbreekt. Vanuit de zoekopdracht krijg je /cag/exhibits/show/landbouw-1750-1880/kruisen_rundvee. Het moet eigenlijk /cag/exhibits/show/landbouw-1750-1880/prille_wetenschap/kruisen_rundvee zijn.

Het deeltje /prille_wetenschap/ ontbreekt om een of andere reden.

**Comment by roxannewyns** [comment]
In orde tot het niveau van de hoofdstukken. De subhoofdstukken geven nog een foutmelding.
Zie bijvoorbeeld themaverhaal Melkbrigade:

Zoekterm op titel hoofdstuk: http://www.hetvirtueleland.be/solr-search/results/?q=vliegende+start 
Resultaat: http://www.hetvirtueleland.be/cag/exhibits/show/melkbrigade/vliegende_start 
Dit klopt

Zoekterm op titel subhoofdstuk: http://www.hetvirtueleland.be/solr-search/results/?q=plechtig+van+start
Resultaat: http://www.hetvirtueleland.be/cag/exhibits/show/melkbrigade/plechtig_van_start
Foutmelding

**Comment by JorisLambrechts** [comment]
de urls worden mee geïndexeerd, ik ben nu aan het herindexeren waarna de urls in orde moeten zijn
