### ISSUE TITLE
collectie - probleem weergave bij ontbreken afbeelding 

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#224]
Als er geen afbeelding is voor een object staat de titel en de beschijving naast elkaar. 
![capture](https://cloud.githubusercontent.com/assets/3798589/16832505/cee38834-49aa-11e6-8f20-897faee5ca53.JPG)

**Comment by JorisLambrechts** [comment]
Het probleem is hier dat de afbeelding niet gevonden wordt (http://resolver.libis.be/IE5800906). In de plaats wordt dan de titel van de afbeelding getoond maar dat is iig geen normaal gedrag.

Volgende links geven geen resultaat:
http://resolver.libis.be/IE5800906
http://resolver.libis.be/IE5801326

Dus in dit geval is er wel een rosetta-object verbonden aan het item maar werkt de url niet. Als er geen rosetta-object is wordt niets getoond, dus dan is dit probleem er niet.

**Comment by roxannewyns** [comment]
ik heb ze toegevoegd
