### ISSUE TITLE
Facebook logo aanpassen in header CAG nieuwsbrief

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#231]
Zie bijlage voor het nieuwe Facebook-logo dat in de header van de CAG-nieuwsbrief gezet mag worden (ter vervanging van het blauwe FB-logo). Link behouden naar FB-pagina "www.facebook.com/CentrumAgrarischeGeschiedenis/"

**Comment by JorisLambrechts** [comment]
zit de bijlage hier in github of in een mail, ik vind het niet meteen

**Comment by JorisLambrechts** [comment]
aangepast via image manager
