### ISSUE TITLE
Uniformiseren lay-out nieuwsbrief 

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#233]
De lay-out van de nieuwsbrief verschilt enigszins van de online versie op HVL wanneer het verzonden wordt. Met name de diverse headings tonen anders. Heading 1 bijv. toont op HVL oranje, maar bij verzending is de heading zwart. Heading 2 is op HVL tekst in een groene balk, maar bij verzending zonder groene balk.

Zie ter referentie bijv. /cag/contactdag_2015 en versie van de verzonden nieuwsbrief in bijlage.

[Nieuwsbrief.docx](https://github.com/libis/CAG/files/708830/Nieuwsbrief.docx)

**Comment by JorisLambrechts** [comment]
Bij dit voorbeeld heeft heading 1 geen inline styling wat de kleur betreft, waardoor het een default waarde krijgt.

Bijvoorbeeld: <h1 style="text-align: center;">"Het kaf en het koren"</h1> moet <h1 style="text-align: center;**color:#f8c400;**">"Het kaf en het koren"</h1> worden.

Voor de achtergrond van heading 2 geld dat ook, in dit voorbeeld komt dat wel niet voor.

Dus alle css die niet inline in het element zit is niet gegarandeerd en kan door de mail-client overschreven worden.
