### ISSUE TITLE
Projecten: afgesloten en lopend project staan onder filter 'objectnaam'

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#234]
De termen 'afgesloten project' en 'lopend project' worden bij projecten in de front-end onder de filter 'objectnaam' weergegeven. Er is voor projecten geen veld 'objectnaam' en deze waardes zouden daar dan ook niet mogen verschijnen. 

Lopen of afgelopen wordt aangegeven d.m.v. feature. 
Dit mag wel als filter verschijnen, maar gewoon niet onder objectnaam.

**Comment by JorisLambrechts** [comment]
er zat foute data in de databank. Er zitten namelijk wel 'object naam' velden in met als text 'lopend project' en 'afgesloten' project

**Comment by roxannewyns** [comment]
Ik ben niet mee. Als je dit record '49309' bekijkt (onder filter objectnaam >lopende projecten), zie ik nergens in het item record lopend project staan. Heb je dit misschien al verwijderd en moet er nog geindexeerd worden?

Als ik zoek op items, dan krijg ik geen resultaten. 
![capture](https://cloud.githubusercontent.com/assets/3798589/22197372/fd2f04fe-e151-11e6-965b-b7ae3599d729.JPG)

**Comment by JorisLambrechts** [comment]
Ik heb ze net uit de databank gehaald, maar ik moet wel nog indexeren. Voor ik ze had verwijdert kon je ze vinden door te zoeken op 'type' project en 'objectnaam niet leeg'

Is er een speciale methode om te indexeren voor CAG of kan dat gewoon via de admin?

**Comment by roxannewyns** [comment]
kan normaal gewoon via admin.

**Comment by JorisLambrechts** [comment]
ziet er ok uit nu (na herindexatie)
